### ISSUE TITLE
Set up Eslint

### ISSUE THREAD

**Issue by josephrexme** [StyleQ/website#25]

**Comment by cannonashlee** [comment]
I pushed the new file to the project but I believe the changes have to be pulled

**Comment by cannonashlee** [comment]
![gitissue1](https://user-images.githubusercontent.com/36325294/77389972-cf8b1a80-6d51-11ea-9800-6ac3094be3ca.PNG)

**Comment by josephrexme** [comment]
Hey @cannonashlee so I started working on the Contribution guides to show how to contribute smoothly with pull requests but I couldn't get it all done last night. I'll update here when done

**Comment by josephrexme** [comment]
Hey @cannonashlee you would have to create a pull request with the changes which add eslint to the project before moving this back to *needs review*. The things that will probably be required for this to be ready for merge will be:

- Add eslint configuration as .eslint.json
- Install all the eslint required packages with npm
- Add a eslint loader to the webpack configuration
